In [1]:
import numpy as np
import torch

In [2]:
a = torch.arange(3*2*2)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a.reshape(3,2,2)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [4]:
a.reshape(2,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [5]:
a.reshape(3,2,2).permute((2,0,1))

tensor([[[ 0,  2],
         [ 4,  6],
         [ 8, 10]],

        [[ 1,  3],
         [ 5,  7],
         [ 9, 11]]])

In [6]:
a.view(3,2,2)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [7]:
a.view(3,2,2).view(2,2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])